<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TraktMyYear.Application\TraktMyYear.Application.csproj" />
    <ProjectReference Include="..\TraktMyYear.Infrastructure\TraktMyYear.Infrastructure.csproj" />
  </ItemGroup>

</Project>
