@TraktMyYear.Api_HostAddress = http://localhost:5000

GET {{TraktMyYear.Api_HostAddress}}/api/v1/auth/status
Accept: application/json

###

GET {{TraktMyYear.Api_HostAddress}}/api/v1/auth/trakt/login

###

GET {{TraktMyYear.Api_HostAddress}}/api/v1/auth/trakt/callback?code=example&state=example

###

DELETE {{TraktMyYear.Api_HostAddress}}/api/v1/auth/trakt

###

GET {{TraktMyYear.Api_HostAddress}}/api/v1/year-reviews/2026
Accept: application/json

###

GET {{TraktMyYear.Api_HostAddress}}/api/v1/year-reviews/2026/movies?sort=rating&direction=desc&page=1&pageSize=10
Accept: application/json

###

GET {{TraktMyYear.Api_HostAddress}}/api/v1/year-reviews/2026/shows?sort=watchedAt&direction=desc&page=1&pageSize=10
Accept: application/json

###

GET {{TraktMyYear.Api_HostAddress}}/api/v1/year-reviews/2026/movie/top?limit=10&minimumRating=8
Accept: application/json

###

GET {{TraktMyYear.Api_HostAddress}}/api/v1/year-reviews/2026/show/top?limit=10
Accept: application/json

###

GET {{TraktMyYear.Api_HostAddress}}/api/v1/year-reviews/2026/movie/export.csv?sort=rating&direction=desc
Accept: text/csv

###

POST {{TraktMyYear.Api_HostAddress}}/api/v1/year-reviews/2026/refresh
